### ISSUE TITLE
Would you please add readable name for the block? (such when viewed with WTHIT/WAYLA)

### ISSUE THREAD

**Issue by ardissaps** [frikinjay/fractalportals#2]
Hellow thank you for the great mod.

Instead of "block.fractasportals.end_fractal" to just simply "End Fractal" or "Fractal End Portals" (also for nether horizontal)
![image](https://user-images.githubusercontent.com/82106625/174285538-6831196d-77c3-41df-8b3b-04c68338dc15.png)

As a comparison like custom portal : 
![image](https://user-images.githubusercontent.com/82106625/174285648-c2f40c08-cb2c-41d1-8d58-3c4fe49dc7bd.png)

**Comment by frikinjay** [comment]
Fixed in 1.3.2
