### ISSUE TITLE
Eden Ring Simple Portal Support

### ISSUE THREAD

**Issue by ardissaps** [frikinjay/fractalportals#5]
Would you like to make custom portal for [Eden Ring](https://www.curseforge.com/minecraft/mc-mods/eden-ring)?
(simple version, maybe just copper frame and ignite it something)
Thank you very much

**Comment by ardissaps** [comment]
Would you please port the Eden Ring portal to 1.18.2 thank you very much

**Comment by frikinjay** [comment]
I will backport these the next time I get some free time. Please make a separate report for it so I can better keep track of it.

**Comment by frikinjay** [comment]
Added in 1.4.0

**Comment by ardissaps** [comment]
> Added in 1.4.0

Thank you very much!


> Please make a separate report for it so I can better keep track of it.

Ok!

**Comment by frikinjay** [comment]
Backported to 1.18.x

**Comment by ardissaps** [comment]
> Backported to 1.18.x

Thank you very much sir! :)

**Comment by frikinjay** [comment]
np!
