### ISSUE TITLE
Server crashes on start up.

### ISSUE THREAD

**Issue by KateReller** [frikinjay/fractalportals#6]
[log.txt](https://github.com/frikinjay/fractalportals/files/9052682/log.txt)

**Comment by frikinjay** [comment]
Cant seem to reproduce with just FabricApi-0.57.0+1.19 and FractalPortals_Fabric-1.19-1.4.0. Can you confirm if it still crashes on your end with just fabric api and the mod?

**Comment by frikinjay** [comment]
nvm, fixed in 1.4.1
